sudo: required

services:
  - docker

env:
  global:
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - BUILD_VERSION=$(date +"%y%m")

jobs:
  include:
    - stage: build, test and push docker image
      script:
        - make
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        #
        - docker tag  ${USER}/dashing:latest ${DOCKER_USERNAME}/docker-dashing:latest
        - docker push ${DOCKER_USERNAME}/docker-dashing:latest
        #
        - docker tag  ${DOCKER_USERNAME}/docker-dashing:latest ${DOCKER_USERNAME}/docker-dashing:${BUILD_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-dashing:${BUILD_VERSION}
        - docker logout
